### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by standardAI**
This pull request fixes typos in comments and docstrings in the codebase.
@abhishekkrthakur

### CODE REVIEW

**Comment by standardAI** [comment]
@abhishekkrthakur

**Comment by standardAI** [comment]
@abhishekkrthakur gently pinging here.

**Comment by standardAI** [comment]
@abhishekkrthakur gently pinging here.

**Comment by abhishekkrthakur** [comment]
hi, if you have more upcoming fixes like this, please add them in this pr

**Comment by standardAI** [comment]
> hi, if you have more upcoming fixes like this, please add them in this pr

That's all for now.

**Pull request merged**
