### PR TITLE
Liger kernel

### PR DESCRIPTION
**Pull request by jaume-ferrarons**
This PR adds support for [Liger Kernel](https://github.com/linkedin/Liger-Kernel) to enable lower training times and reduce memory usage.

It implements:
* Validating `liger-kernel` is available.
* Adds training `liger-kernel` parameter to llm finetuning tasks.
* Switching to `liger-kernel`'s model loader then installed, enabled by the user and the LLM's type is supported by `liger-kernel`.

### CODE REVIEW

**Comment by aflah02** [comment]
Hey
I just happened to stumble on this PR by accident. I noticed that you're using imports from the liger library however I believe it is now deeply integrated within transformers - https://huggingface.co/docs/transformers/main/en/trainer#liger-kernel
Any reason you chose to not use this route? Just curious if there are any performance issues with the transformer version or something

**Comment by jaume-ferrarons** [comment]
Hello @aflah02!

Thank you for letting me now, I wasn't aware of it. I'll update the PR to enable if using the trainer instead 👍

**Comment by jaume-ferrarons** [comment]
@aflah02 , I've update the PR, it's much simpler but it isn't compatible with peft now 😞 . (see issue here: https://github.com/huggingface/transformers/issues/34016).

I hope the issue is going to be solved soon.

**Comment by aflah02** [comment]
Ah nice
Yep seems like a easy to fix thing based on the discussion under that issue

**Pull request closed without merging**
