### PR TITLE
logging, termination for Windows users on run_app.py

### PR DESCRIPTION
**Pull request by gulf1324**
logging, terminating code changes for ```Windows``` users with ```if sys.platform```, ```else``` statement.

### CODE REVIEW

**Comment by abhishekkrthakur** [comment]
after these changes are you able to use the app and train models on windows?

**Comment by gulf1324** [comment]
@abhishekkrthakur Yes, I haven't tested all kinds of trainings, but tested with ```ImageClassification/google-vit-base-patch16-224```, it works.

**Comment by abhishekkrthakur** [comment]
via WSL?

**Comment by gulf1324** [comment]
No, just on local machine with Windows11

**Comment by abhishekkrthakur** [comment]
could you fix code quality? 
run: `make style && make quality`

**Review by abhishekkrthakur — APPROVED** [review]

**Pull request merged**
